eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@registry:8761/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 10000

ribbon:
  ReadTimeout: 15000
  ConnectTimeout: 15000

spring:
  http: 
    encoding: 
      force: true
      charset: UTF-8
      enabled: true
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .html
  redis:
    host: redis
    port: 6379
    password:
    database: 0
    timeout: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 500
      min-idle: 0
  data:
    mongodb:
      uri: mongodb://mongodb:27017/springboot-db
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  rabbitmq:
    host: rabbitmq
  sleuth:
    sampler:
      percentage: 1
    integration:
      enabled: false
    scheduled:
      skip-pattern: "^org.*HystrixStreamTask$"
  jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
  datasource:
        name: ceplat
        url: ${ce.database.url:jdbc:mysql://192.168.99.160:3306/oct_bm?useSSL=false&useUnicode=true&characterEncoding=UTF8}
        username: ${ce.database.username:root}
        password: ${ce.database.password:123456}
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: ${ce.database.class:com.mysql.jdbc.Driver}
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
security:
  basic:
    path: /swagger-ui.html
    enabled: true
  user:
    name: admin
    password: ${MONITOR_SERVER_PASSWORD:admin}
management:
  security:
    enabled: false
swagger:
    basepackage: ${ce.doc.base:com.sgcctd}
    service:
        name: ${ce.doc.name:lizp}
        description: ${ce.doc.des:api}
        developer: ${ce.doc.dev:hzkj}
server:
  tomcat:
    uri-encoding: UTF-8
  undertow:
    uri-encoding: UTF-8
logging:
  level:
    com.netflix: error
xxl:
  job:
    accessToken: ''
    admin:
      addresses: http://jobadmin:8080/xxl-job-admin
    executor:
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: -1
      ip: ''
